# https://mherman.org/blog/dockerizing-a-react-app/
FROM kubevious/react-builder:12
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY src-react/package.json ./
COPY src-react/package-lock.json ./
RUN npm install
COPY src-react/ ./
CMD ["npm", "start"]