version: "1.0"
stages:
  - "clone"
  - "build"
  - "docker"
steps:
  
  clone_init:
    title: Init Clone
    stage: clone
    image: codefresh/cli
    shell: bash
    commands:
      - export PRODUCT_NAME="ui"
      - cf_export PRODUCT_NAME="${PRODUCT_NAME}"
      - cf_export GITHUB_TOKEN=$(codefresh get context github --decrypt -o yaml | yq -y .spec.data.auth.password)

  main_clone:
    type: "git-clone"
    title: Clone Main Repo
    description: "Cloning main repository..."
    repo: "kubevious/${{CF_REPO_NAME}}"
    revision: "${{CF_BRANCH}}"
    stage: clone

  prepare_repo:
    title: Prepare Repository
    stage: build
    image: kubevious/react-builder:12
    working_directory: ${{main_clone}}/src
    shell: bash
    commands:
      - npm ci

  build_mock_service:
    title: Build with Mock Services
    stage: build
    image: kubevious/react-builder:12
    working_directory: ${{main_clone}}/src
    shell: bash
    commands:
      - unset CI
      - export REACT_APP_MOCKED_DATA=true
      - npm run build

  build_real_service:
    title: Build with Real Services
    stage: build
    image: kubevious/react-builder:12
    working_directory: ${{main_clone}}/src
    shell: bash
    commands:
      - unset CI
      - echo $REACT_APP_MOCKED_DATA
      - npm run build

  build_docker:
    title: "Building Docker Image"
    type: build
    image_name: "kubevious/${{PRODUCT_NAME}}"
    stage: docker
