version: "1.0"
stages:
  - "clone"
  - "build"
  - versioning
  - "push"
steps:
  
  clone_init:
    title: Init Clone
    stage: clone
    image: codefresh/cli
    shell: bash
    commands:
      - export PRODUCT_NAME="ui"
      - cf_export PRODUCT_NAME="${PRODUCT_NAME}"
      - cf_export GITHUB_TOKEN=$(codefresh get context github --decrypt -o yaml | yq -y .spec.data.auth.password)

  main_clone:
    type: "git-clone"
    title: Clone Main Repo
    description: "Cloning main repository..."
    repo: "kubevious/${{CF_REPO_NAME}}"
    revision: "${{CF_BRANCH}}"
    stage: clone

  inject_version:
    title: Inject Version
    stage: build
    image: codefresh/cli
    shell: bash
    commands:
      - echo "module.exports = \"v1.2.3\";" > /codefresh/volume/${PRODUCT_NAME}/src/src/version.js
      - cat /codefresh/volume/${PRODUCT_NAME}/src/src/version.js
      - cf_export PRODUCT_VERSION="${PRODUCT_VERSION}"
      - cf_export DOCKER_TAG="${CF_BRANCH}-${PRODUCT_VERSION}"

  build:
    title: "Building Docker Image"
    type: build
    image_name: "kubevious/${{PRODUCT_NAME}}"
    stage: build
