version: "1.0"
stages:
  - "clone"
  - "build"
  - "prepare"
  - "validate-mock"
steps:
  
  clone_init:
    title: Init Clone
    stage: "clone"
    image: codefresh/cli
    shell: bash
    commands:
      - export PRODUCT_NAME="ui"
      - cf_export PRODUCT_NAME="${PRODUCT_NAME}"
      - cf_export GITHUB_TOKEN=$(codefresh get context github --decrypt -o yaml | yq -y .spec.data.auth.password)
      - cf_export CYPRESS_CACHE_FOLDER="/codefresh/volume/cypress_cache"
      - ls -la /codefresh/volume/
      - rm -rf /codefresh/volume/${{CF_REPO_NAME}}
      - ls -la /codefresh/volume/

  main_clone:
    title: Clone Main Repo
    stage: "clone"
    type: "git-clone"
    repo: "kubevious/${{CF_REPO_NAME}}"
    revision: "${{CF_BRANCH}}"

  build_mock_ui_docker:
    title: "Building Mock UI Image"
    stage: build
    type: build
    image_name: "kubevious/${{PRODUCT_NAME}}-mock"
    dockerfile: "Dockerfile.mock"
    disable_push: true

  prepare:
    title: Prepare Test
    stage: prepare
    image: 'kubevious/node-builder:12'
    working_directory: "${{main_clone}}"
    shell: bash
    commands:
      - "echo NODE_ENV=${NODE_ENV}"
      - npm ci
      - "echo '{ \"baseUrl\": \"http://ui:80\" }' > cypress.json"

  run_ui_mock_test:
    title: Test Mock UI
    stage: validate-mock
    image: cypress/included:4.8.0
    working_directory: ${{main_clone}}
    services:
      composition:
        ui:
          image: ${{build_mock_ui_docker}}
          ports:
            - 80
          environment:
            - "BACKEND_URL=localhost:4001"
      readiness:
        image: 'curlimages/curl:7.70.0'
        timeoutSeconds: 30
        commands:
          - "curl http://ui:80"
    commands:
      - npm run cy:run-ci

