version: "1.0"
stages:
  - "clone and prepare"
  - "build"
  - "mock-server"
  - "real-server"
  - "docker"
steps:
  
  clone_init:
    title: Init Clone
    stage: "clone and prepare"
    image: codefresh/cli
    shell: bash
    commands:
      - export PRODUCT_NAME="ui"
      - cf_export PRODUCT_NAME="${PRODUCT_NAME}"
      - cf_export GITHUB_TOKEN=$(codefresh get context github --decrypt -o yaml | yq -y .spec.data.auth.password)

  main_clone:
    type: "git-clone"
    title: Clone Main Repo
    description: "Cloning main repository..."
    repo: "kubevious/${{CF_REPO_NAME}}"
    revision: "${{CF_BRANCH}}"
    stage: "clone and prepare"

  prepare_repo:
    title: Prepare Repository
    stage: "clone and prepare"
    image: kubevious/react-builder:12
    working_directory: ${{main_clone}}/src
    shell: bash
    commands:
      - export CYPRESS_CACHE_FOLDER=/codefresh/volume/Cypress
      - cf_export CYPRESS_CACHE_FOLDER=${CYPRESS_CACHE_FOLDER}
      - npm ci

  run_mock_e2e_tests:
    title: "Running Mock Server E2E Tests"
    stage: "mock-server"
    image: kubevious/react-builder:12
    working_directory: ${{main_clone}}/src
    commands:
      - export REACT_APP_MOCKED_DATA=true
      - export CYPRESS_VIDEO=false
      - echo ${CYPRESS_CACHE_FOLDER}
      - npm run ci

  build_mock_service:
    title: Build with Mock Services
    stage: "mock-server"
    image: kubevious/react-builder:12
    working_directory: ${{main_clone}}/src
    shell: bash
    commands:
      - unset CI
      - export REACT_APP_MOCKED_DATA=true
      - npm run build

  run_real_e2e_tests:
    title: "Running Real Server E2E Tests"
    stage: "real-server"
    image: kubevious/react-builder:12
    working_directory: ${{main_clone}}/src
    commands:
      - export BACKEND_URL=http://demo.kubevious.io
      - export CYPRESS_VIDEO=false
      - npm run ci

  build_real_service:
    title: Build with Real Services
    stage: "real-server"
    image: kubevious/react-builder:12
    working_directory: ${{main_clone}}/src
    shell: bash
    commands:
      - unset CI
      - echo $REACT_APP_MOCKED_DATA
      - npm run build

  build_docker:
    title: "Building Docker Image"
    type: build
    image_name: "kubevious/${{PRODUCT_NAME}}"
    stage: docker