version: "1.0"
stages:
  - "clone and prepare"
  - "build"
  - "test"
  - "mock-server"
  - "real-server"
  - "docker"
steps:
  
  clone_init:
    title: Init Clone
    stage: "clone and prepare"
    image: codefresh/cli
    shell: bash
    commands:
      - export PRODUCT_NAME="ui"
      - cf_export PRODUCT_NAME="${PRODUCT_NAME}"
      - cf_export GITHUB_TOKEN=$(codefresh get context github --decrypt -o yaml | yq -y .spec.data.auth.password)

  main_clone:
    title: Clone Main Repo
    stage: "clone and prepare"
    type: "git-clone"
    repo: "kubevious/${{CF_REPO_NAME}}"
    revision: "${{CF_BRANCH}}"

  build_mock_ui_docker:
    title: "Building Mock UI Image"
    stage: build
    type: build
    image_name: "kubevious/${{PRODUCT_NAME}}-mock"
    dockerfile: "Dockerfile.mock"

  prepare_test_params:
    title: "Prepare Test Params"
    stage: test
    shell: bash
    image: codefresh/cli
    working_directory: ${{main_clone}}
    commands:
      - "echo '{ \"baseUrl\": \"http://ui:80\" }' > src/cypress.json"
      - cat src/cypress.json

  run_ui_mock_test:
    title: Test Mock UI
    stage: test
    image: cypress/included:4.8.0
    working_directory: ${{main_clone}}/src
    shell: bash
    commands:
      - pwd
      - ls -la
      - cypress run
    services:
      composition:
        ui:
          image: ${{build_mock_ui_docker}}
          ports:
            - 80
          environment:
            - "BACKEND_URL=http://localhost:4001"
      readiness:
        image: 'byrnedo/alpine-curl'
        timeoutSeconds: 30
        commands:
          - "curl http://ui:80" 
