version: "1.0"
stages:
  - "clone"
  - "build"
  - versioning
  - "push"
steps:
  
  clone_init:
    title: Init Clone
    stage: clone
    image: codefresh/cli
    shell: bash
    commands:
      - export PRODUCT_NAME="ui"
      - cf_export PRODUCT_NAME="${PRODUCT_NAME}"
      - cf_export GITHUB_TOKEN=$(codefresh get context github --decrypt -o yaml | yq -y .spec.data.auth.password)
      - cf_export CICD_REPO_PATH="/codefresh/volume/cicd.git"

  main_clone:
    type: "git-clone"
    title: Clone Main Repo
    description: "Cloning main repository..."
    repo: "kubevious/${{CF_REPO_NAME}}"
    revision: "${{CF_BRANCH}}"
    stage: clone

  cicd_clone:
    title: Clone CI/CD Repo
    stage: clone
    image: 'alpine/git:latest'
    working_directory: "${{main_clone}}/.."
    commands:
      - pwd
      - ls -la
      - rm -rf cicd.git
      - 'git clone https://${{CF_REPO_OWNER}}:$GITHUB_TOKEN@github.com/${{CF_REPO_OWNER}}/cicd.git cicd.git'
      - ls -la
      - ls -la cicd.git/

  inject_version:
    title: Inject Version
    stage: build
    image: codefresh/cli
    shell: bash
    working_directory: "${{CICD_REPO_PATH}}/${{PRODUCT_NAME}}"
    commands:
      - pwd
      - ls -la
      - ../process-version-bump.sh
      - source version.sh
      - echo "module.exports = \"${PRODUCT_VERSION}\";" > /codefresh/volume/${PRODUCT_NAME}/src/src/version.js
      - cat /codefresh/volume/${PRODUCT_NAME}/src/src/version.js
      - cf_export PRODUCT_VERSION="${PRODUCT_VERSION}"
      - cf_export DOCKER_TAG="${PRODUCT_VERSION}"
      - cf_export DOCKER_TAG="dev"

  build:
    title: "Building Docker Image"
    type: build
    image_name: "kubevious/${{PRODUCT_NAME}}"
    stage: build

  push:
    title: "Pushing image to DockerHub"
    type: "push"
    stage: "push"
    image_name: "kubevious/${{PRODUCT_NAME}}"
    registry: "dockerhub"
    candidate: "${{build}}"
    tags:
      - latest
      - "${{DOCKER_TAG}}"

  process_versioning:
    title: Process Versioning
    stage: push
    image: codefresh/cli
    shell: bash
    working_directory: "${{CICD_REPO_PATH}}"
    commands:
      - pwd
      - ls -la
      - /codefresh/volume/cicd.git/git-commit-push.sh "Version bump for ${PRODUCT_NAME} to ${PRODUCT_VERSION}"
